### ISSUE TITLE
Account not working with 2FA

### ISSUE THREAD

**Issue by CBainx** [nextcloud/ocsms#157]
### Steps to reproduce
1. Install nextcloud SMS app.
2. Install android sms app.
3. Enable nextcloud 2 factor authentication.
4. Try to add sync account to android.

### Expected behaviour
Login procedure should ask for 2fa code.

### Actual behaviour
Login fails, wrong password.

### Server configuration

**NextCloud/ownCloud version:** Nextcloud 11

**PHP version:** 7

**HTTPd server:** apache2 (ubuntu)

**HTTPS:** yes

### Client configuration

**Android version:** 6

**Phone:** HTC One M9

**ownCloud SMS app version:**  0.23.2

**Comment by nerzhul** [comment]
2FA is not compatible with this application as we use a passive synchronization protocol using web api. How can we use 2FA using standardized protocol ? Is there any application password like google ?

**Comment by Diablofan** [comment]
App Passwords do work with the app, go generate one in your user settings @CBainx and Nextcloud would just authenticate using that as the password instead of using the real user password. I just used it to log in and sync my SMSs and it started chugging away.

Proper 2FA support in the android app would be nice, but I don't think this is the right place for it.

**Comment by nerzhul** [comment]
@Diablofan can i ask you to send us a PR on README.md to explain how to use create this password for 2FA ?
