### ISSUE TITLE
App Update Phone Sync (ocsms) 13.0.2 

### ISSUE THREAD

**Issue by kaiowas1974** [nextcloud/ocsms#237]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_ocsms_smsdatas CHANGE `sms_address` `sms_address` VARCHAR(512) NOT NULL': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.

Detaillierte Protokollmeldungen 
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_ocsms_smsdatas CHANGE `sms_address` `sms_address` VARCHAR(512) NOT NULL': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.

**Comment by lmo-reira** [comment]
Salut Nerzhul, je viens de tomber sur la même erreur que cet utilisateur, je te mets + d'info ici.

### Steps to reproduce
1. Go to nextcloud web interface
2. Click on the "update" for ocsms 

### Expected behaviour
Successful update.

### Actual behaviour
The update fails.

### Server configuration

**Nextcloud/ownCloud version:**  
$OC_VersionString = '13.0.0';
$OC_Build = '2018-02-06T00:39:26+00:00 3b4285e13f6b1ec074b98466f49e189101f090bc';

**PHP version:** PHP 7.0.19-1

**HTTPd server:** Apache/2.4.25

**Database engine & version:** mariadb-server 10.1.26-0+deb9u1

### Logs

```
Mise à jour vers 13.0.0

Journaux détaillés
Préparation de la mise à jour
Réglage du niveau de journalisation à "déboguage"
Mode de maintenance activé
Mise à jour du schéma de la base de données
Base de données mise à jour
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_ocsms_smsdatas CHANGE `sms_address` `sms_address` VARCHAR(512) NOT NULL': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
```

**Comment by nerzhul** [comment]
Hello, it's another time a MySQL issue... Thanks to this engine.

Please look at https://stackoverflow.com/questions/30761867/mysql-error-the-maximum-column-size-is-767-bytes/30767600

Ensure innodb_large_prefix = ON is set in your my.cnf at least
