### ISSUE TITLE
Showing conversations for some contacts is not working properly

### ISSUE THREAD

**Issue by adi2k5** [nextcloud/ocsms#282]
### Steps to reproduce
1. Try to load conversation for 'specific' contact
2. Conversation is not loaded

### Expected behaviour
Conversation should be loaded after picking a contact from the left menu

### Actual behaviour
After upgrade to v 2.0.2, when I choose some specific contacts in the contact list, conversations are not loaded and I have only message "Choose conversation from the list to load it", even if SMS for given contact does exist in database. Specific contacts are the ones, that have their names joined for some reason in web application, even though in DB they are shown properly, like "NameSurname" instead of "Name Surname". Ie.:
MariaDB [xxx]> select id,sms_id,sms_address from oc_ocsms_smsdatas where sms_address="Jxxx Uxxx";
+-----+--------+---------------+
| id  | sms_id | sms_address   |
+-----+--------+---------------+
| 164 |  13200 | Jxxx Uxxx |
| 367 |  12997 | Jxxx Uxxx |
+-----+--------+---------------+
2 rows in set (0.00 sec)

While in web app the name is being shown as joined name and surname: "JxxxUxxx", and conversation can't be loaded. 
[![tmp.jpg](https://i.postimg.cc/vT98wc9v/tmp.jpg)](https://postimg.cc/4HfRz4WK)
I have completely uninstalled application, dropped all oc_sms_* DBs, cleared all caches, installed application back, and re-synced messages, but to no avail, issue still remains. 

Also, as can be seen on screenshot, on vivaldi browser there is some problem with styling, name icons are squeezed one on top of another. On firefox it looks fine.
Changing manually height parameter in #app-mailbox-peers > ul to anything other than 100% (ie. to fit-content) seems to help with this case.

### Server configuration

**Nextcloud/ownCloud version:**
14.0.3
**PHP version:**
7.2.11
**HTTPd server:**
lighttpd
**Database engine & version:** 
mariadb 10.2
### Client configuration

**Android version:**
Oreo
**Phone:**
Honor 9
**Nextcloud SMS app version:**
2.0.4

**Comment by e-alfred** [comment]
> Also, as can be seen on screenshot, on vivaldi browser there is some problem with styling, name icons are squeezed one on top of another. On firefox it looks fine.

This happens on all Chromium-based browsers.

**Comment by nerzhul** [comment]
yeah the code conversion is a little bit sensible... i don't have time to refactor it properly, if someone wants, go ahead :)

**Comment by elisa204** [comment]
I also had the same issue.
* Nextcloud 15.0.5 with Phone Sync 2.1.1, language German.
* On my Smartphone (Android 9): Nextcloud SMS in the version 2.0.6 
* "Wähle eine Unterhaltung zum Laden aus der Liste aus." seems to be similar to "Choose conversation from the list to load it"

What I have done since I last looked in Phone Sync (in the German Version: Telefon-Sync):
* Updated my phone from Android 8.x to Anroid 9
* Activated Signal Messenger and copied SMS from Standard-SMS-App into the Signal App
* Updated and synct to my phone all my contacts in Nextcloud Contacts (in the German Version: Kontakte) and I also changed the names
** from a) like "John" and "KENNEDY" to b) "John" and "Kennedy" in the name fields and changed the display name back to "John KENNEDY".
** from a) "My_xyz_PHONENAME" to b) "My xyz.PHONENAME" (see here underlines to space and dot)

=> Phone Sync/Telefon-Sync show me the version b) to each contact and the "Wähle eine Unterhaltung ..." as above. The url shows to this contacts as of "/apps/ocsms/?phonenumber=+438901234567" (here: +43=Austria, 890 means the Austrian mobile prefix, 1234567 means the telephone number)
=> SMS from phonenumbers are not in my (Nextcloud) contacts are shown well in Phone Sync/Telefon-Sync. The url shows in this cases instead of the "phonenumber=+438901234567" the version like "/apps/ocsms/?phonenumber=Instagram" or SMS coming from the Signal Server as "/apps/ocsms/?phonenumber=Info".

TIA and sorry if something is very bad English ...

**Comment by codeling** [comment]
I have created a pull request with an a bit more sophisticated fix than proposed above - with the fix above conversations for people not in my address book would not be shown; with the one from the pull-request, for me all conversations are loaded properly.

Incidentally, I just noticed, that in contrast to what the original poster mentioned, I have the problem for *all* conversations where a contact exists in my database, and I don't see the mentioned Name/Surname "joining"... so maybe  @adi2k5 you can test whether this fix makes things work for you?
